### ISSUE TITLE
Provide sample for Using MQTT protocol

### ISSUE THREAD

**Issue by yhilem** [strimzi/amqp-kafka-bridge#83]
Hi team,

I found amqp-kafka-demo (https://devhub.io/repos/ppatierno-amqp-kafka-demo) that shows that it's possible to publish messages to an Apache Kafka topic when using an MQTT client and amqp-kafka-bridge, but I dont't understand how.

Can you please provide us with an example ?

We have use cases to consume kafka messages with mqtt on Android smartphones.

Thanks
Youcef HILEM

**Comment by ppatierno** [comment]
Hi,

the official repo you are referring about is this one : https://github.com/ppatierno/amqp-kafka-demo
The MQTT support is availble thanks to the usage of the AMQP - Kafka bridge inside a deployment with the EnMasse "messaging as a service" platform. This platform has an MQTT gateway which allows connections on MQTT, translating them into AMQP 1.0. After that, the bridge comes in action bridging AMQP to Kafka so with that demo the steps are : MQTT -> AMQP -> Kafka.

Btw I'm doing a refactoring work on this AMQP - Kafka bridge in order to support other protocols (i.e. MQTT) directly.

**Comment by yhilem** [comment]
Hi,
Thank you very much for your response.
I look forward to this new refactoring to produce / consume messages directly in kafka via mqtt.
Our stack runs with Apache kafka on Red Hat OpenShift.

Thanks
Youcef HILEM

**Comment by ppatierno** [comment]
Interesting, have you taken a look to this project as well ? 

https://github.com/EnMasseProject/barnabas

It's about running the Kafka "ecosystem" on Kubernetes and OpenShift.

**Comment by yhilem** [comment]
Not yet.
We have just upgraded to OpenShift from 3.4 to 3.5.
StatefulSets are in technical preview release. 
I will test this on my laptop with minishift.

Thanks
Youcef HILEM

**Comment by ppatierno** [comment]
Feel free to ask any questions you have or opening issues in the related GitHub project.
Looking forward to hear from you.

**Comment by yhilem** [comment]
Yes thanks. I will surely come back because we have strong needs for interaction with our partner customers and our operational fleet equipped with android smartphones.
Our message bus is kafka.
The external standard protocols retained are http and mqtt.
The amqp-kafka-bridge component seem to me to meet the need.

**Comment by ppatierno** [comment]
@yhilem I'm going to close this issue because I think I answer your question. Looking forward to hear from you.
